import { Wrapper } from "@src/components/wrapper";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	viewport: "width=device-width, initial-scale=1",
	icons: [
		{
			rel: "icon",
			url: "/favicon.ico",
		},
	],
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<Wrapper>
				<body>{children}</body>
			</Wrapper>
		</html>
	);
}
